### ISSUE TITLE
/usr/sbin/sendmail: not found

### ISSUE THREAD

**Issue by elmaester** [bitnami/bitnami-docker-matomo#100]
**Description**

I'm trying to send an email report, but the UI says
`An error occurred while sending 'HTML Email Report - 1.today.1.en - pSAtU5fKukX1gw0tkNNPbuewm3uslTRDCCGV4bcG.html' to . Error was 'Could not instantiate mail function.'`
So I looked at the log and one line there says:
`matomo_1   | sh: 1: /usr/sbin/sendmail: not found`
And indeed I explored inside the container and no such file exists.
Is this expected behavior? Is some extra configuration required? I'm surprised that batteries are not included. Please advise how best to proceed.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-matomo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
