### ISSUE TITLE
Bitnami apps on Azure App Service

### ISSUE THREAD

**Issue by ptemmer** [bitnami/bitnami-docker-matomo#103]
### Name and Version

bitnami/matomo:4.7.1

### What steps will reproduce the bug?

Has someone tried running this on Azure App Service for containers?
I have tried tried to do so, although not very successful.

I attached an Azure Files Share mount to the App Service service to persist /bitnami/matomo.
Although the (external) Mysql database gets populated, and first installation seems to go through fine (I can see files being persisted in the Azure File Share), upon container restart it hangs on the following step:

```
        info "Updating default plugins in persisted data"
        rsync -a "$MATOMO_BASE_DIR"/plugins/ "$MATOMO_VOLUME_DIR"/plugins/
```
Eventually I get a timeout  (after over 2min) and the container restart again, and again, and..

Possibly an incompatibility using rsync and the Azure Files share?

### What do you see instead?

.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-matomo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by ptemmer** [comment]
I've been digging a bit deeper into this, and rather than any incompatibility it's performance related.
Copying over files to the SMB fileshare seems terribly slow. 
Unfortunately Azure File Shares are the only supported read/write storage available for Azure App Service.
