### ISSUE TITLE
Using several of the `MATOMO_*` environment variables to update configuration should be possible after the first initialization

### ISSUE THREAD

**Issue by Bengrunt** [bitnami/bitnami-docker-matomo#107]
### Name and Version

bitnami/matomo:4.8.0-debian-10-r13

### What steps will reproduce the bug?

1. Deploy and configure Matomo once
2. Realize you're behind a reverse proxy and get wrong IP addresses in logs and data
3. Read the docs and [see](https://github.com/bitnami/bitnami-docker-matomo#reverse-proxy-configuration-options) the following environment variables:
    - `MATOMO_ENABLE_ASSUME_SECURE_PROTOCOL`
    - `MATOMO_ENABLE_FORCE_SSL`
    - `MATOMO_ENABLE_PROXY_URI_HEADER`
    - `MATOMO_PROXY_CLIENT_HEADER`
5. Inject these variables in the existing deployment, restart the container

### What is the expected behavior?

I would expect to be able to set these kind of configuration after the initial bootstrap of my Matomo deployment.

### What do you see instead?

The running configuration of Matomo remains unchanged. The environment is ignored.

### Additional information

Reading the code, it seems to me that it's due to the fact that these settings along with several other (database settings, reverse proxy, smtp, etc) are within [an `if/else` statement](https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libmatomo.sh#L106) that gets escaped after the first initialization.

Looking at [`matomo-env.sh`](https://github.com/bitnami/bitnami-docker-matomo/blob/e4838846062213c712697cb43978bafd0503d820/4/debian-10/rootfs/opt/bitnami/scripts/matomo-env.sh#L92) it is stated quite clearly. However I can't seem to grasp why this is so ?

What if my SMTP provider configuration changes at some point? Would I have to scrape the persisted configuration and start from scratch? What is the process here?

Even scripts located in `/docker-entrypoint-init.d/*` won't be processed which is quite misleading.

Thanks for the insight!

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-matomo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by ianschmitz** [comment]
The same applies for other `MATOMO_*` variables such as `MATOMO_DATABASE_HOST`, etc.
