### ISSUE TITLE
Matomo 4.9.0. build

### ISSUE THREAD

**Issue by kevin-shelaga** [bitnami/bitnami-docker-matomo#109]
### Name and Version

bitnami/matomo

### What is the problem this feature will solve?

add support for matomo 4.9.0

### What is the feature you are proposing to solve the problem?

add support for matomo 4.9.0

**Comment by carrodher** [comment]
Thanks for letting us know, this new version was already detected by our tracking system but it requires some manual changes. The team is currently working on it. We will update this issue once released the new version.

**Comment by carrodher** [comment]
Hi, we directly released the new version (4.9.1), see https://github.com/bitnami/bitnami-docker-matomo/commit/2a14f92b4a1f2075fa184a5fbbb89ced2eb68fd6
