### ISSUE TITLE
Notable Changes version mistake

### ISSUE THREAD

**Issue by S0obi** [bitnami/bitnami-docker-matomo#110]
### Name and Version

README

### What steps will reproduce the bug?

Read README.md

### What do you see instead?

In the README https://github.com/bitnami/bitnami-docker-matomo/blob/master/README.md#3141-debian-10-r79, latest notable change stated that 3.14.1-debian-10-**r79** has been migrated to non-root user approach.

The exact image tag that migrated to such behavior seems to be 3.14.1-debian-10-**r82**

Diff : https://github.com/bitnami/bitnami-docker-matomo/compare/3.14.1-debian-10-r79...3.14.1-debian-10-r82

**Comment by rafariossaa** [comment]
Hi,
  Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-matomo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
