### ISSUE TITLE
PHP Redis Extention

### ISSUE THREAD

**Issue by dieisraels** [bitnami/bitnami-docker-matomo#112]
### Name and Version

bitnami/bitnami-docker-matom:4.10.1

### What is the problem this feature will solve?

Matomo supports caching the tracking in redis before persisting it in the database. However, the PHP in the image does not contain a Redis extension. Because of missing root privileges, this cannot be post-installed. A separate Docker image must be created for this function, which inherits from this one. 

### What is the feature you are proposing to solve the problem?

The Docker image should already contain the PHP Redis extension (https://pecl.php.net/package/redis).

**Comment by javsalgar** [comment]
Hi!

Please, note this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version.
