### ISSUE TITLE
Modified Ports not working

### ISSUE THREAD

**Issue by Prithivi-Rajan** [bitnami/bitnami-docker-matomo#113]
### Name and Version

bitnami/matomo:4.9.1

### What steps will reproduce the bug?

I'm trying to build an image with a base of 4.9.1 version and use ports 80 & 443 instead of 8080 & 8443 as my infra has some dependencies. When trying to containerize the image in AWS Fargate I'm getting below error.

An invalid port was specified in the environment variable `APACHE_HTTPS_PORT_NUMBER`: privileged port requested.

My Docker File:
```Dockerfile
FROM bitnami/matomo:4.9.1
USER 0
#Installing few packages
USER 1001
ENV APACHE_HTTP_PORT_NUMBER=80
ENV APACHE_HTTPS_PORT_NUMBER=443
EXPOSE 80 443 
```

### What do you see instead?

 When trying to containerize the image in AWS Fargate I'm getting below error.
```
An invalid port was specified in the environment variable APACHE_HTTP_PORT_NUMBER: privileged port requested.
An invalid port was specified in the environment variable APACHE_HTTPS_PORT_NUMBER: privileged port requested.
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-matomo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
