### ISSUE TITLE
'docker pull bitnami/matomo' not working

### ISSUE THREAD

**Issue by tschach** [bitnami/bitnami-docker-matomo#13]
**Description**
I am trying to pull bitnami/matomo using `docker pull bitnami/matomo` on Windows 10, but it does not work. I also tried  `docker pull bitnami/matomo:latest` and `docker pull bitnami/matomo:3` with the same error message (see below). Also, the [list of available versions] (https://hub.docker.com/r/bitnami/matomo/tags/) in the Docker Hub Registry is empty.

**Describe the results you received:**
If called without a tag:

> Using default tag: latest
> Error response from daemon: manifest for bitnami/matomo:latest not found

If called with a tag:

> Error response from daemon: manifest for bitnami/matomo:latest not found

**Additional information you deem important (e.g. issue happens only occasionally):**
`docker pull bitnami/piwik` still works, so maybe this is just a temporary issue while updating from piwik to matomo?

**Version**
- Output of `docker version`:
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64
Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
- Output of `docker info`:
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 8
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d4c8407
ID: 3LXY:BTQX:ARNP:DCIM:ENZJ:FI7I:PQMS:QBB3:LWWG:FPDP:VUWG:TOOE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 49
 System Time: 2018-02-02T10:31:58.042497Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by adriengibrat** [comment]
please publish bitnami/matomo  to docker hub ;)

**Comment by dbarranco** [comment]
Hi @tschach @adriengibrat 

Thanks for reporting this.
It seems that our CI/CD process failed and the matomo image was not correctly upload to the s3buckets, so the `bitnami-pkg install matomo ...` is not working.

We're currently working on this, so in the next hours we will release a revision fixing this.
Sorry for the inconveniences.

Kind regards.

**Comment by dbarranco** [comment]
Hi @tschach @adriengibrat 

I would like you to notify that we have released the [3.3.0-1 tag](https://github.com/bitnami/bitnami-docker-matomo/releases/tag/3.3.0-r1) which includes the fix for the issue with the continious integration.

I'm proceeding to close this. Feel free to open a new thread if you find any other issue.
Kind regards.
