### ISSUE TITLE
Typo in the name

### ISSUE THREAD

**Issue by ramv** [bitnami/bitnami-docker-matomo#17]
https://github.com/bitnami/bitnami-docker-matomo/blob/1c14855d7e1bbd08d3af623e9260b46c6b0459e9/3/Dockerfile#L30
```  MATOM_WEBSITE_NAME```
should be
```  MATOMO_WEBSITE_NAME```

**Comment by juan131** [comment]
Hi @ramv 

Thanks for reporting it!! I just created a new revision of the image fixing this issue (see 3.4.0-r18)

Please take a look at it and feel free to close the issue once you consider it solved.
