### ISSUE TITLE
Upgrade to Matomo 3.6.0

### ISSUE THREAD

**Issue by btok** [bitnami/bitnami-docker-matomo#22]
Hi,
Although its very new (released yesterday), I would like to point out that Matomo 3.6.0 was released.
This release contains some important security features and fixes so I would appriciate the Bitnami image upgraded asap.
I tried upgrading from Matomo UI however when i check for upgrades, None are shown (eg getting a message i am using the latest version). 
I understand this could take some time so any other ideas on how i can manually update the image while the Bitnami image is not updated ? 
Thanks !

**Comment by andresbono** [comment]
Hi @btok, we have just released the latest version of Matomo: [3.6.0-debian-9-r0](https://github.com/bitnami/bitnami-docker-matomo/releases/tag/3.6.0-debian-9-r0) and [3.6.0-ol-7-r0](https://github.com/bitnami/bitnami-docker-matomo/releases/tag/3.6.0-ol-7-r0).

-Andrés B.

**Comment by btok** [comment]
Thanks @andresbono ! Appriciate the fast response !
