### ISSUE TITLE
Custom logo is not persisted in the /bitnami volume

### ISSUE THREAD

**Issue by valentinab25** [bitnami/bitnami-docker-matomo#23]
**Description**

Matomo custom logo images are not saved in the /bitnami volume, so they are deleted on any upgrade.

**Steps to reproduce the issue:**

1. Add a new logo ( from Settings, General Settings, Branding settings)
2. Stop and delete the matomo container
3. Recreated the matomo container

**Describe the results you received:**

The custom logo is missing, the old "Matomo" logo is present

**Describe the results you expected:**

The custom logo should be preserved. 

**Additional information you deem important (e.g. issue happens only occasionally):**

Logo related images are saved in /opt/bitnami/matomo/misc/user. It should be a link to a directory in the /bitnami volume.

**Version**

Does not matter, because all versions will have the same problem for the image.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment]
Hi @valentinab25, thanks for reporting this issue and giving us detailed information. We are going to investigate it and we will keep this issue updated.

Thanks again!

**Comment by alemorcuq** [comment]
Hi, @valentinab25.

We have released two new containers that persist custom logos:

```
3.13.1-debian-9-r5
3.13.1-ol-7-r5
```

Please, have a look and let us know if you find any issues.
