### ISSUE TITLE
Update to Matomo 3.6.1

### ISSUE THREAD

**Issue by michidk** [bitnami/bitnami-docker-matomo#25]
**Description**

Old Matomo version used

**Steps to reproduce the issue:**
 
1. Install Image
2. Log in 
3. Warning appear

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/3979930/47256344-ece1f800-d47e-11e8-9020-a886bd5c4c79.png)

**Describe the results you expected:**

No warning, because Matomo is on Version 3.6.1

**Comment by carrodher** [comment]
Thanks for letting us know, currently we are working on the new version, it should be released during this week.

**Comment by michidk** [comment]
3.9.1 is the latest version now
