### ISSUE TITLE
Set up auto archiving cron job not working

### ISSUE THREAD

**Issue by NaturalFigurehead** [bitnami/bitnami-docker-matomo#26]
**Description**

I'm trying to set up auto-archiving https://matomo.org/docs/setup-auto-archiving/

Doesn't seem to be working.

**Steps to reproduce the issue:**

Followed the steps in the article.

Also tried running my own command based on the bitnami matomo directory:
`sudo su tb-matomo-admin -s /bin/bash -c "/opt/bitnami/php/bin/php /opt/bitnami/apps/matomo/htdocs/core core:archive --url=https://mywebsite.com"`

**Describe the results you received:**

No output to console. No archive.

**Describe the results you expected:**

A success message in the console, and the ability to view stats in matomo.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm using the bitnami matomo installer for Azure.

**Version**

- Output of `docker version`:

```
The program 'docker' is currently not installed. You can install it by typing:
sudo apt install docker.io
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Azure

**Comment by javsalgar** [comment]
Hi,

It seems to me that this is a question about our Matomo cloud image. Could you open the question in community.bitnami.com, this is for containers and helm charts.

Thanks
