### ISSUE TITLE
File integrity errors starting with bitnami/matomo:3.10.0

### ISSUE THREAD

**Issue by valentinab25** [bitnami/bitnami-docker-matomo#34]
**Description**

**Steps to reproduce the issue:**

1. Go to Settings,  System Check on a new installation  of bitnami/matomo:3.10.0 or bitnami/matomo:3.11.0 

**Describe the results you received:**
File integrity errors:

```
Errors below may be due to a partial or failed upload of Matomo files.
--> Try to reupload all the Matomo files in BINARY mode. <--

File size mismatch: /opt/bitnami/matomo/misc/cron/.htaccess (expected length: 103, found: 149)
Missing file: /opt/bitnami/matomo/vendor/tecnickcom/tcpdf/tools/.htaccess
```
**Describe the results you expected:**

The usual message:
```
Files were found in your Matomo, but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: How to install Matomo.html
File to delete: .buildcomplete


To delete all these files at once, you can run this command:
rm "/opt/bitnami/matomo/How to install Matomo.html" "/opt/bitnami/matomo/.buildcomplete"
```

**Additional information you deem important (e.g. issue happens only occasionally):**

It is reproducible with a new/empty installation using the bitnami/matomo installation documentation .  The error did not appear after a manual upgrade, but it's present in bitnami/matomo images.

**Version**

 bitnami/matomo:3.10.0 and  bitnami/matomo:3.11.0 have this problem.

**Comment by andresbono** [comment]
Hi @valentinab25, we have just tried to reproduce the issue but we are getting the expected result:

![image](https://user-images.githubusercontent.com/1057973/61881387-d9c0f480-aef6-11e9-97a6-bd3ce7ef6381.png)

Is there anything else that you suggest to reproduce it? Can you try to run the containers without volumes associated? Just for debugging purposes. Is the result different?

**Comment by valentinab25** [comment]
You can see the error messages in your print-screen. They are after the usual "rm ... " message ( the last 4 lines of the report ).

**Comment by andresbono** [comment]
😱I was expecting to see it in a different position of the messages. I missed it.

After checking it, that message is expected, you can find more information here: https://docs.bitnami.com/aws/apps/matomo/administration/check-system/.
