### ISSUE TITLE
Matomo GeoIP2 support

### ISSUE THREAD

**Issue by Natgho** [bitnami/bitnami-docker-matomo#38]
Hi,
How can I add to GeoIP2 support to Matomo in this docker compose?

**Comment by juan131** [comment]
Hi @Natgho 

The GeoIP2 Apache module is not enabled in the Apache server shipped in this Docker image by default. We have docs about how to install it as you can check in the link below:

- https://docs.bitnami.com/general/apps/redmine/configuration/install-modules-php/#geoip2

These are the steps I followed to add it in this Docker Image:

- Check the module is not enabled by default:

```bash
$ docker-compose up -d
$ docker-compose exec matomo bash
# apachectl -M
```

- Download/compile/enable the module

```bash
# install_packages build-essential libgeoip-dev
# curl -LO https://github.com/maxmind/geoip-api-mod_geoip2/archive/1.2.10.tar.gz
# tar xfz 1.2.10.tar.gz
# cd geoip-api-mod_geoip2-1.2.10
# apxs -i -a -lGeoIP -c mod_geoip.c
```

- Check the module is not enabled by default:

```
# apachectl -M
Loaded Modules:
...
 geoip_module (shared)
```

**Comment by Natgho** [comment]
Thank you for participation. I will try :)
