### ISSUE TITLE
Cannot mount volume on Azure Web App for Container?

### ISSUE THREAD

**Issue by marco27384** [bitnami/bitnami-docker-matomo#39]
I have the Matomo Docker Image from https://github.com/bitnami/bitnami-docker-matomo that I run in a Web App for Container on Azure with my own Azure Container Registry (ACR).

Also, I have an Azure Storage Account with a File Share available.

What I would like to achieve is to mount a persistent storage (File Share from Az Storage Account) to it so I don't loose the config and plugins installed of Matomo.

I tried using the Mount Storage (Preview), but I couldn't get it to work.

Name: matomo_data Storage Type: Azure Files Mount path: /bitnami

As described in: https://github.com/bitnami/bitnami-docker-matomo#persisting-your-application

This didn't work.

I also tried via the setting WEBSITES_ENABLE_APP_SERVICE_STORAGE = true on the Web App for Containers, but apparently seems not to do anything either.

I would appreciate any hints here, as otherwise I would have to make a custom docker image, push it to the registry, with a custom docker compose file, which I would like to avoid.

Thanks a lot in advance for any hints on this!

**Comment by miguelaeh** [comment]
Hi @marco27384 ,
If you have the container already on your ACR and you have your File Share configured it should be enough to use the az command setting `--azure-file-volume-mount-path /bitnami` as the mount path and configuring the rest of parameters with your custom information. You can refer to [this](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files#deploy-container-and-mount-volume---cli) to have an idea about how to pass the parameters.

**Comment by marco27384** [comment]
Hi @miguelaeh Thanks a lot - I did it this way, now all from a sudden it seems to work. However, this slows down Matomo to such an extreme level that it becomes basically unusable. I am comparing on the same Azure Subscription with the same setup (but no storage mounted) and accessing from the same device/network, the instance of Matomo WITHOUT storage mounted is multiple times faster.
As soon as I remove the storage and re-run the instance, it's fast again.

I chose the PREMIUM storage on Azure and optimized for File Share.

If this is what is expected, then Matomo bitnami image becomes unusable.

Thanks for any advice!

**Comment by miguelaeh** [comment]
Hi @marco27384 ,
I am not an expert on Azure so I am not really sure about what could be the problem. You could try to analyze the disk usage by matomo with the azure tools. Check [this](https://cloud.netapp.com/blog/azure-disk-performance-how-to-analyze-and-monitor-issues). I hope it can help you to discover what is happening.
