### ISSUE TITLE
Matomo JavaScript tracker file "/matomo.js" doesn't seem to be accessible

### ISSUE THREAD

**Issue by pelotom** [bitnami/bitnami-docker-matomo#40]
I have this warning in my System Check page in Matomo:

![image](https://user-images.githubusercontent.com/128019/64662889-da5a0f80-d3fe-11e9-896a-d5b0adde5a34.png)

which seems to be preventing plugins installed from the marketplace from working properly. It's not clear to me where `matomo.js` lives; it doesn't seem to get created in the root of the `matomo_data` volume which is where I would expect to find it, and creating an empty writeable file there seems to have no effect either.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that I was able to reproduce the issue. We will work on releasing a new revision of the container that fixes the issue. As it is not something critical, we cannot guarantee an ETA. However, as soon as it is fixed, I will update the thread.

Thanks for reporting

**Comment by javsalgar** [comment]
Not stale.

Update: I've been able to remove most of the warnings in the system check. I will update the ticket when the image is released.

**Comment by javsalgar** [comment]
Hi,

Just a quick note to let you know that we released a new revision that fixes all the warnings in the system check. Note that the docker-compose.yaml has changed as well.

https://github.com/bitnami/bitnami-docker-matomo/commit/3d3da353ecaf3cfc0bf60692b25292b22a1e1b8a
