### ISSUE TITLE
Cant access Matomo with Kubernetes install

### ISSUE THREAD

**Issue by castfe** [bitnami/bitnami-docker-matomo#43]
**Description**
I installed this Matomo image via kubectl (kubectl apply -f test.yaml). I have changed test.yaml so that test-matomo targetPort is 2000 (instead of 80)

The two pods are running, but when I access the url http://`minikube ip`:2000 and I get no response. Curious to know if I'm missing something or doing something wrong. I'm very new to k8s.

**Steps to reproduce the issue:**

1. Change test-matomo targetPort to 2000 in test.yaml
2. $ kubectl apply -f test.yaml
3. $ open http://`minikube ip`:2000

**Describe the results you received:**

No page is opened

**Describe the results you expected:**

Matomo page should open

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df9ba
  Built:            Wed Sep  4 16:55:50 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 60
  Running: 53
  Paused: 0
  Stopped: 7
 Images: 41
 Server Version: 18.09.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a4bc1d432a2c33aa2eed37f338dceabb93641310
 runc version: N/A
 init version: N/A (expected: )
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.15.0
 Operating System: Buildroot 2018.05.3
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 9.524GiB
 Name: minikube
 ID: GT6I:ZPQK:WSN4:IEH3:RDUM:HK6I:XRVR:2GE2:RTJO:CH6Z:KBTW:65Y3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=virtualbox
 Experimental: false
 Insecure Registries:
  10.96.0.0/12
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

- Output of `minikube version`:
```
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6
```

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @castfe, can you share the modifications that you have done to the `test.yaml` file?

**Comment by castfe** [comment]
I have done no modifications to test.yaml

**Comment by castfe** [comment]
I was able to get it running and access it via https://$(minikube ip):32001 by changing the test-matomo server into this though:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-matomo
  name: test-matomo
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32000
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    nodePort: 32001
    protocol: TCP
    targetPort: 443
    name: https
  selector:
    app: test-matomo
```
If this is not correct, please let me know (again, I'm very new to k8s so don't assume anything hehe)

**Comment by andresbono** [comment]
Nice! As you specified a service type: `NodePort`, it should work and you should be able to access the application.

**Comment by andresbono** [comment]
In any case, please note that the `test.yaml` file is only for testing purposes, but it is not recommended to use it into production. Unfortunately, we don't provide Matomo for Kubernetes, but you can find the Helm charts that we maintain here: https://github.com/bitnami/charts.
