### ISSUE TITLE
Special characters in SMTP password break configuration

### ISSUE THREAD

**Issue by YKWeyer** [bitnami/bitnami-docker-matomo#45]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

**Steps to reproduce the issue:**

1. Start the container with a `SMTP_PASSWORD` variable containing special characters (e.g: `6VQ)9cL4?sD3L27J2!mzBv$9PTj&TR#v`)

**Describe the results you received:**

The container starts, but the initialisation of matomo fails with message:

```
Unable to read INI file {/opt/bitnami/matomo/config/config.ini.php}: Syntax error in INI configuration:

  Your host may have disabled parse_ini_file().

   [Piwik\Container\ContainerDoesNotExistException]
   The root container has not been created yet.
```
**Describe the results you expected:**

Matomo should start.

**Additional information you deem important (e.g. issue happens only occasionally):**

Looking the generated `config.ini.php` file, it turns out the password is not wrapped in quotes, causing any special char in value to make whole ini file invalid. 
```ini
[mail]
transport=smtp
password=6VQ)9cL4?sD3L27J2!mzBv$9PTj&TR#v
; Special chars should be wrapped in double quotes:
password="6VQ)9cL4?sD3L27J2!mzBv$9PTj&TR#v"
```

**Version**

Tested and reproduced with container `bitnami/matomo:3.13.0`

**Comment by carrodher** [comment]
Hi, I was able to reproduce the issue. I just created an internal task to solve the issue, we will release a new revision of the matomo image including the fix for this issue.

Thanks for reporting it!

**Comment by carrodher** [comment]
Hi,

I just released a new version of the matomo image. Tags newer than`3.13.0-debian-9-r36` or `ol-7	3.13.0-ol-7-r51` should contain the fix.

```yaml
  matomo:
    image: 'bitnami/matomo:latest'
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASSWORD=asdh#*%.,ashd
      - SMTP_PROTOCOL=tls
      - SMTP_PORT=587
```
```
$ docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED              STATUS              PORTS                                      NAMES
35394f5029bb        bitnami/matomo:latest   "/app-entrypoint.sh …"   About a minute ago   Up 58 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   petete_matomo_1
b1fff08a976b        bitnami/mariadb:10.3    "/entrypoint.sh /run…"   About a minute ago   Up 59 seconds       3306/tcp                                   petete_mariadb_1

$ docker exec -it 35394f5029bb cat /opt/bitnami/matomo/config/config.ini.php | grep -A 8 '\[mail\]'
[mail]
transport=smtp
port=587
host=smtp.gmail.com
username=your_email@gmail.com
password="asdh#*%.,ashd"
type=Plain
encryption=tls
```
Can you confirm if the new images works fine for your purpose? Thanks!

**Comment by YKWeyer** [comment]
Hi @carrodher , 

I can confirm it now works! :+1:
