### ISSUE TITLE
Database port must be 3306

### ISSUE THREAD

**Issue by YKWeyer** [bitnami/bitnami-docker-matomo#47]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

The port in env. variable `MARIADB_PORT_NUMBER` doesn't seem to be saved in configuration, and Matomo always tries to connect using port `3306`

**Steps to reproduce the issue:**

1. Start the container with a `MARIADB_PORT_NUMBER` value other than `3306`

> ℹ️ See this [docker-compose.yml](https://gist.github.com/YKWeyer/7506872da8136fc94fa654899442318f) to reproduce the issue. The MariaDB default port `3306` is mapped to hosts `33060`, and the Matomo container uses the bridge connection to access the database.
> 
> [You might need to replace `172.17.0.1` by your local  bridge gateway](https://docs.docker.com/network/network-tutorial-standalone/)

**Describe the results you received:**

The container starts, and MySQL connection test succeeds:
```
matomo_1_5805b43a185f | mysql-c INFO  Trying to connect to MySQL server
matomo_1_5805b43a185f | mysql-c INFO  Found MySQL server listening at 172.17.0.1:33060
matomo_1_5805b43a185f | mysql-c INFO  MySQL server listening and working at 172.17.0.1:33060
```
But accessing the website shows 
> Cannot connect to the database:
>
> SQLSTATE[HY000] [2002] No such file or directory

**Describe the results you expected:**

Matomo should work and display its dashboard.

**Additional information you deem important (e.g. issue happens only occasionally):**

I wonder if it might be connected with the port parameter missing in the `databaseSetup` action in `com.bitnami.matomo/helpers.js`: 
```
    {
      action: 'databaseSetup',
      host: databaseHandler.connection.host,
      username: databaseHandler.connection.user,
      password: databaseHandler.connection.password,
      dbname: databaseHandler.connection.name,
      adapter: 'MYSQLI',
    },
```

**Comment by alemorcuq** [comment]
Hi, @YKWeyer.

Thank you for reporting this. I believe you are right, since according to [Matomo's Installation Guide](https://matomo.org/docs/installation/#mysql-database-setup) you need to specify your database server in the format `host:port` if you want to use a port that's not the default 3306.

We are working on a fix.

**Comment by alemorcuq** [comment]
We released two new containers that now specify the database server as `host:port`:

```
3.13.0-debian-9-r39 
3.13.0-ol-7-r56
```

Let us know if there's any problem.

**Comment by YKWeyer** [comment]
Hi @alemorcuq 

Thank you for the patch! I can confirm it now works as expected :+1:
