### ISSUE TITLE
Container tagging issues

### ISSUE THREAD

**Issue by YKWeyer** [bitnami/bitnami-docker-matomo#49]
**Description**

When using the Docker image as a source, it is currently possible to track following tags:
* `{MATOMO_MAJOR}-{OS}-{OS_MAJOR}`(e.g: `3-debian-10`)
* `{MATOMO_MAJOR}.{MATOMO_MINOR}.{MATOMO_PATCH}` (e.g: `3.13.1`)
* `{MATOMO_MAJOR}.{MATOMO_MINOR}.{MATOMO_PATCH}-{OS}-{OS_MAJOR}-r{INCREMENT}` (e.g: `3.13.1-debian-10-r1`)
* `{MATOMO_MAJOR}.{MATOMO_MINOR}-r{INCREMENT}`(e.g: `3.13.1-r1`)

It is not possible to specify a Matomo patch with a specific OS version (something like: `3.13.1-debian-9` or `3.13.1-debian-10`), which might broke build of everyone using the matomo version as identifier when the OS gets updated.
You might consider adding an intermediate tag logic without the bitnami release:
`{MATOMO_MAJOR}.{MATOMO_MINOR}.{MATOMO_PATCH}-{OS}-{OS_MAJOR}`

Also, I noticed some older tags get overridden after an OS upgrade,: [`3.13.1-r1`](https://hub.docker.com/layers/bitnami/matomo/3.13.1-r1/images/sha256-6cbe218f53664a5578f3d921b76df8be1a5857547305a48f12d8f536bf48f79f) is actually newer than [`3.13.1-r5`](https://hub.docker.com/layers/bitnami/matomo/3.13.1-r5/images/sha256-7dd4760dd61505ee5a25b95039c76133a360bb9341ec4105183bbeac804c51fa)

**Comment by andresbono** [comment]
Hi @YKWeyer, We only maintain one version of the different operative systems. Recently, we switched from Debian 9 to 10.

> Also, I noticed some older tags get overridden after an OS upgrade,: 3.13.1-r1 is actually newer than 3.13.1-r5

Do you mean that the application is auto-updated when the container is ran?

**Comment by YKWeyer** [comment]
Hi @andresbono ,

> We only maintain one version of the different operative systems. Recently, we switched from Debian 9 to 10.

This is how I became aware of this issue. I use your Docker container as a base image to then add further requirements (Redis client, Shibboleth SP, and so on…). The tag used to base the image on was `bitnami/matomo:3.13.1`, allowing me to have control over the patch version of Matomo yet get the latest available Bitnami patches everytime the image gets built.
When you released the debian-10 update under the same tag, it broke the image build because some dependencies were missing or renamed in debian-10. I now use `bitnami/matomo:3.13.1-debian-9-r5` until I ensure all dependencies work with debian-10. 
I guess it might happen again during the next Debian major update if it doesn't coincide with a major/minor Matomo release (updating the container to debian-10 when you release `bitnami/matomo:4.0.0` in March would have been no issue)

This would have been avoided with the possibility to have both the OS-Version _AND_ the Matomo patch version specified in tag (e.g: `3.13.1-debian-10`, `3.13.1-debian-9`, `3.13.1-ol-7`) without your internal increment.

**Comment by andresbono** [comment]
Thanks for your suggestions, @YKWeyer. We will evaluate the possibility of including those new tags.

**Comment by andresbono** [comment]
Hi again @YKWeyer, the restart of the revision counter shouldn't be a problem for the next OS update as we made a fix in the release logic.

About your suggestion on adding a new rolling tag specifying the operative system, I'm afraid that we won't add it for now. We consider that we have too many tags already so adding more could be even more confusing.
