### ISSUE TITLE
Azure Blob Storage is now read-only. No other storage mount is usable

### ISSUE THREAD

**Issue by adisaljusi** [bitnami/bitnami-docker-matomo#53]
**Description**
We are using the https://github.com/bitnami/bitnami-docker-matomo image. We used to use the Azure Storage Account with blob storage. Since February 2020, blob storage is read-only.

We used Azure blob storage and it was fine, not the fastest but usable for our users. But, now we have to use Azure FileShare. It somehow works but with an usable Matomo site. Response time is awful and it takes the dashboard five minutes to fully load.

**Steps to reproduce the issue:**

1. WebApp -> Container Settings
2. Path Mappings and add new Azure Mount Storage
3. Select Storage Account and FileShare
4. Specify mount path

**Describe the results you received:**

Slow and unusable Matomo instance.

**Describe the results you expected:**

Usable Matomo instance like with blob storage

**Comment by marcosbc** [comment]
@adisaljusi This seems like an issue very specific to the Azure cloud, and unfortunately there's little we can do about it. Could you contact Azure support?

**Comment by adisaljusi** [comment]
Can you recommend how Bitnami would create persistence settings for the Bitnami Matomo docker container? Or someone I can get in contact with? Otherwise the container is not useful for the Azure cloud and the only option would to use a VM.

**Comment by marcosbc** [comment]
Sorry if I didn't make made myself clear enough in my previous comment.

What I wanted to express is that the Azure Blob Storage should not be read-only. You must modify its configuration for it to be writable, which we understand needs to be done via the Azure management panel. If you find issues, we recommend you to contact Azure, as it is an Azure Cloud specific issue and not related with the Bitnami Docker image.

Note that the Bitnami Matomo container image **requires** the persistent volume directory (`/bitnami`) to be writable, even if you persist data or not.
