### ISSUE TITLE
Create a non-root image

### ISSUE THREAD

**Issue by S0obi** [bitnami/bitnami-docker-matomo#54]
**Description**

The current docker image use the ROOT user to run the Matomo instance (PHP).
It will be lovely to have a Bitnami non-root image to increase the level of security. 

**Steps to reproduce the issue:**

Using the official Security Info plugin, we are able to get this diagnostic :

![image](https://user-images.githubusercontent.com/4180104/81276111-dc8a7180-9052-11ea-9fbb-d05fdef4c064.png)

**Describe the results you received:**

The Security Info plugin reports that PHP is running with a privilege user (root).

**Describe the results you expected:**

The Security Info plugin should report that a dedicated non-root user is running PHP (www-data for example).

**Comment by thpham** [comment]
I totally agree!  It would be awesome.

I was trying to find how I could create a PR to fix this, but as matomo seems to be installed in the docker image via [bitnami-pkg](https://github.com/bitnami/bitnami-docker-matomo/blob/master/3/debian-10/Dockerfile#L16) and [download custom bitnami](https://github.com/bitnami/bitnami-docker-matomo/blob/master/3/debian-10/prebuildfs/usr/sbin/bitnami-pkg#L155-L164) Stacksmith app bundle, which is then installed on the image with [nami](https://github.com/bitnami/nami)...

I was not able to find on github how those custom bitnami app package are built ?

Maybe a bitnami member could help ?

CC. @tompizmor 

Thank you.

**Comment by beltran-rubo** [comment]
Thanks @thpham @S0obi, let me clarify two different concepts that I think we are mixing here.

1. The report from Matomo. It says "PHP maybe be executing as a privileged user" so it is not saying that is the case right now. In this case the container ships Apache with mod_php and the server is running as "daemon" user that is a non-privileged user. This is a secure configuration and it is very common in web servers.

2. Move the container to a "non-root" container. This is a recommended practice to avoid any processes running as root into the container. This is required for some K8s platform like Tanzu Kubernetes Grid or OpenShift. We are moving apps to this configuration so it is part of our roadmap but we can not tell you an specific deadline for this.

At the end the result will be similar, the Apache process is running as a non-privileged user in both cases. I hope it helps.

**Comment by thpham** [comment]
@beltran-rubo 

Thank you for the clarifications, it helps !

Second questions about stacksmith ? how could we contribute back to the open source package you are bundling and use for installation in most of your docker images ?

Thank you.

**Comment by beltran-rubo** [comment]
We don ot have those components available in independent repos (we have hundreds of them) but you can see the code in the container itself or you can download it in your laptop:

```
wget https://downloads.bitnami.com/files/stacksmith/matomo-3.13.5-0-linux-amd64-debian-10.tar.gz
```

We know it is not easy to contribute them, that is why most of the infrastructure containers are now based in 'bash' rather than 'javascript'. We will need to continue moving web apps to that approach.

Thanks!
