### ISSUE TITLE
Tag Manager permissions error

### ISSUE THREAD

**Issue by aneumann-cdlx** [bitnami/bitnami-docker-matomo#60]
**Description**

I'm encountering the below error when I attempt to navigate to matomo.example.com/index.php?module=TagManager&action=manageVersions&idSite=1&period=day&date=yesterday&idContainer=<id>#?idContainerVersion=2

**Steps to reproduce the issue:**

1. Login to Matomo
2. Select the site you want to work on
3. Click Tag Manager on the top right next to the gears
4. On the left sidebar, select versions 
![image](https://user-images.githubusercontent.com/57628133/89908359-c93ff280-dbbb-11ea-9d2f-183277035971.png)

**Describe the results you received:**

I receive the following error page:

![image](https://user-images.githubusercontent.com/57628133/89908304-b7f6e600-dbbb-11ea-8744-28dab48164f3.png)

```

An error occurred

Matomo couldn't write to some directories (running as user 'daemon').

Try to Execute the following commands on your server, to allow Write access on these directories:

    chown -R daemon:daemon /opt/bitnami/matomo
    find /opt/bitnami/matomo/js -type f -exec chmod 644 {} \;
    find /opt/bitnami/matomo/js -type d -exec chmod 755 {} \;

If this doesn't work, you can try to create the directories with your FTP software, and set the CHMOD to 0755 (or 0777 if 0755 is not enough). To do so with your FTP software, right click on the directories then click permissions.

After applying the modifications, you can refresh the page.

If you need more help, try Matomo.org.
```

**Describe the results you expected:**

[The tag manager versions page is displayed](https://matomo.org/docs/tag-manager/#versions)

**Additional information you deem important (e.g. issue happens only occasionally):**

This occurs on a brand new matomo cluster and matomo site.

It also appears this may affect the behavior of viewing Tag Manager containers in the first place? 
![image](https://user-images.githubusercontent.com/57628133/89908705-33589780-dbbc-11ea-8be0-4e85efd8e743.png)

Logo files and settings are persisted to disk and last across redeployments. I can provide more specific persistence information if needed (currently using K8s PVCs)

**Version**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 146
  Running: 131
  Paused: 0
  Stopped: 15
 Images: 366
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.13.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.24GiB
```

- Output of `docker-compose version` (if applicable):

N/A

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Helm to K8S.

**Comment by miguelaeh** [comment]
Hi @aneumann-cdlx ,
Thank you very much for reporting this issue.

```
    find /opt/bitnami/matomo/js -type f -exec chmod 644 {} \;
    find /opt/bitnami/matomo/js -type d -exec chmod 755 {} \;
```
It seems the files already have the permissions that the above commands will provide.
So, the issue should be related to owner of the `/opt/bitnami/matomo` folder. Since the container is a root container, you should be able to change the owner of that folder. Could you check in a non-production environment if executing:
``` 
   chown -R daemon:daemon /opt/bitnami/matomo
```
solves the problem ?
Regards

**Comment by aneumann-cdlx** [comment]
>... Since the container is a root container, you should be able to change the owner of that folder. Could you check in a non-production environment if executing:
> 
> ```
>    chown -R daemon:daemon /opt/bitnami/matomo
> ```
> 
> solves the problem ?
> Regards

We are currently attempting to accomplish what you suggest via an image using the below dockerfile using the latest bitnami image as a base image / parent image. 

```
FROM bitnami/matomo:latest
RUN mkdir -p /opt/bitnami/matomo/js && \
    chown -R 1:1 /opt/bitnami/matomo #1:1 = matomo container daemon user && \
    find /opt/bitnami/matomo/js -type f -exec chmod 644 {} \; && \
    find /opt/bitnami/matomo/js -type d -exec chmod 755 {} \;

ENTRYPOINT ["/app-entrypoint.sh"]
CMD [ "/run.sh" ]
```

However, when we attempt to start the container, it is unable to start with the following error. We might have incorrect settings in our dockerfile, we continue working on it, but I post it here just in case this helps. 

![image](https://user-images.githubusercontent.com/57628133/91188693-9881b200-e6bf-11ea-9d50-59d4751d37e4.png)

**Comment by aneumann-cdlx** [comment]
This appears to be solved nicely with your suggestion @miguelaeh, great idea.

We used the following dockerfile (after learning that Dockerfile comments must start at the beginning of the line. The container created based on the below started just fine and enables the UI to show in the Tag Manager as expected. 

```
FROM bitnami/matomo:latest
# for the below chown, 1:1 is the uid of the matomo container daemon user
RUN mkdir -p /opt/bitnami/matomo/js && \
    chown -R 1:1 /opt/bitnami/matomo && \
    find /opt/bitnami/matomo/js -type f -exec chmod 644 {} \; && \
    find /opt/bitnami/matomo/js -type d -exec chmod 755 {} \;

ENTRYPOINT ["/app-entrypoint.sh"]
CMD [ "/run.sh" ]
```


![image](https://user-images.githubusercontent.com/57628133/91190683-d7b10280-e6c1-11ea-81c5-6e0860664d4d.png)

**Comment by aneumann-cdlx** [comment]
Closing as resolved.

**Comment by miguelaeh** [comment]
Thank you for the confirmation @aneumann-cdlx, we will take care to modify the image to solve the issue.
Regards.

**Comment by aneumann-cdlx** [comment]
> 
> 
> Thank you for the confirmation @aneumann-cdlx.
> I checked the permissions of the image in a fresh deployment, but I can see they are correct, did you edit the image in some way before getting the error?? It is just to confirm if we need to fix it.
> Regards.

We did not modify the image in any way. We used bitnami:matomo-latest as our image source.
