### ISSUE TITLE
TagManager gets deactivated periodically

### ISSUE THREAD

**Issue by b-r-u-h** [bitnami/bitnami-docker-matomo#61]
**Description**

since a couple of weeks the TagManager gets deactivated periodiacally and has to be manually enabled in System --> Plugins.
We use the image "[bitnami/matomo:3.14.0](https://hub.docker.com/r/bitnami/matomo)" in Kubernetes. This also happened in the version before (3.13.4).
Is there any option or configuration we're missing that persists the enabled plugins this?

**Steps to reproduce the issue:**

Sadly this can't be reproduced. Container was not restarted and none of the admins have deactivated it.

**Describe the results you received:**

In "System" --> "Plugin" the TagManager plugin is displayed as disabled 

**Describe the results you expected:**

Once activated the Plugin stays activated the whole time.

**Additional information you deem important (e.g. issue happens only occasionally):**

There is no pattern to recognize, e.g. Specific day or time, no redeployment. Last time it was deactivated is 2 days ago and before it happened on the 5th of August.

**Version**

- Output of `docker version`:

We are not using Docker but Kubernetes Version 1.13.5

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Database is [bitnami/mariadb:10.3.21](https://hub.docker.com/r/bitnami/mariadb)

Thanks in Advance!

**Comment by dani8art** [comment]
Hi @b-r-u-h thanks for opening this issue,

I was not able to reproduce the issue using 3.13.4 nor 3.14.0, I found another one that could be related to this, did you face the same?

```
Directories with write access for Tag Manager  /opt/bitnami/matomo/js

To fix this error on your GNU/Linux system, try typing in the following command(s)

chmod a+w /opt/bitnami/matomo/js
```

BTW, we always recommend using fixed docker image tags in k8s/production environment since k8s will be rescheduling pods and containers so if they are using `3.14.0` instead of `3.14.0-debian-10-rXX` k8s could be modifying your containers, each time it is scheduled by k8s.

**Comment by b-r-u-h** [comment]
Hi @dani8art ,
Thanks for your reply and having a look at this issue.
I was also not able to reproduce this issue in another environment (e.g. local docker). 

About the issue you mentioned: Yes we did. But we resolved this with a "postStart" hook like this since it got mentioned in the "System Check":

```
        lifecycle:
          postStart:
            exec:
              command: 
              - "sh"
              - "-c"
              - >
                 chmod a+w /opt/bitnami/matomo/js
```
So there is no issue in enabling the Plugin in the first place but that it gets deactivated randomly.

So this always kind of resolves upon starting the container. So there is no issue in enabling the Plugin in the first place but that it gets deactivated randomly. I guess then this can't be that, unless this could be changing again in an already running environment?

And thanks for the hint about the image tags, will have a look at that. But this should not cause any problems with the TagManager, right?

**Comment by dani8art** [comment]
Hi @b-r-u-h, 

I reviewed our configuration logic and files but I found nothing related to the plugins configuration, this kind of configuration is managed by the Matomo application and it seems to be stored in the database by the application itself.

I think [Matomo Community ](https://forum.matomo.org/)could help you more on this since it seems to be a problem related to the plugin and app instead of the configuration logic. 

> And thanks for the hint about the image tags, will have a look at that. But this should not cause any problems with the TagManager, right?

When upgrading to a new version of the image we execute a DB migration script which is given in the application bundle and also updates plugins to the version that Matome shipped. This last could affect the plugin activate/deactivate issue.

```js
    $app.info(`${$app.name} has being already initialized, restoring...`);
    $app.info('Updating default plugins to the shipped version...');
    $app.helpers.updateDefaultPlugins();
    volumeFunctions.restorePersistedData($app.dataToPersist);
    const execStatus = php.execute('console core:update --yes', {
      cwd: $app.installdir, retrieveStdStreams: true,
    });
    if (execStatus.code !== 0) {
      throw new Error('The installation of Matomo failed.');
    }
```

**Comment by b-r-u-h** [comment]
Hi @dani8art ,

Alright i will open an issue with the Matomo Guys.
Thanks, really appreciate your help here!

**Comment by b-r-u-h** [comment]
Hi @dani8art ,
sorry to bother you again with this but i opened an issue directly in the TagManager Github project and was sent back to you: https://github.com/matomo-org/tag-manager/issues/269

We have the file "config.ini.php" in following directory: /bitnami/matomo/config (a symlink in "/opt/bitnami/matomo/config" points to the file). Do we have to put it in another directory?

Thanks again!

**Comment by b-r-u-h** [comment]
Hi @dani8art ,

Thanks for investigating on this and sorry for the delay in my answer, i had to reproduce this first.

Strangely i'm not able to confirm this behavior. All other Plugins keep running if i disable the TagManager. Same behavior with other Plugins. 

Meanwhile i was able to resolve the Original issue (or at least i found a workaround if the Pod crashes). The change of the "config.ini.php" is now done as one of the first steps upon a deployment of Matomo in k8s. It seems the issue was that we indeed had a correct "config.ini.php" but the file was altered too late, so basically Matomo was already running and did not read the changes in the configuration file. This does not resolve the issue of the random crashes the TagManager runs into, but at least if the pod dies.

But now as we start the Plugin automatically there is still the Problem that we manually have to deploy a new Version like this: "TagManager" --> "Publish" --> Select an Environment --> "Create new version and publish Release".
Do you know by chance if there is some way to automate this? Some option in the "config.ini.php"?

Thanks already!

**Comment by dani8art** [comment]
Hi @b-r-u-h thank you for keeping us updated,

Please, could you extend a bit more how did you solve the original issue? I would like to understand better, also if you can share these k8s manifest it would be useful.

Regarding the new question, I would like to understand your goal, I mean, do you want to automatically install plugins updates? isn't it done by matomo container already?

Thanks.
