### ISSUE TITLE
 INFO  Initializing matomo matomo_1   | Error executing 'postInstallation': "size" argument must not be negative

### ISSUE THREAD

**Issue by ematpad** [bitnami/bitnami-docker-matomo#63]
**Description**

Trying to install Matomo using docker-compose. getting the below error during the installation

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**
$ docker-compose logs -f
Attaching to docker_matomo_1, docker_mariadb_1
mariadb_1  | mariadb 07:23:37.77
mariadb_1  | mariadb 07:23:37.77 Welcome to the Bitnami mariadb container
mariadb_1  | mariadb 07:23:37.77 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | mariadb 07:23:37.77 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | mariadb 07:23:37.77
mariadb_1  | mariadb 07:23:37.77 INFO  ==> ** Starting MariaDB setup **
mariadb_1  | mariadb 07:23:37.79 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1  | mariadb 07:23:37.79 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | mariadb 07:23:37.80 INFO  ==> Initializing mariadb database
mariadb_1  | mariadb 07:23:37.81 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb_1  | mariadb 07:23:37.81 INFO  ==> Setting user option
mariadb_1  | mariadb 07:23:37.81 INFO  ==> Using persisted data
mariadb_1  | mariadb 07:23:37.83 INFO  ==> Running mysql_upgrade
mariadb_1  | mariadb 07:23:37.84 INFO  ==> Starting mariadb in background
mariadb_1  | mariadb 07:23:40.03 INFO  ==> Stopping mariadb
mariadb_1  |
mariadb_1  | mariadb 07:23:43.04 INFO  ==> ** MariaDB setup finished! **
mariadb_1  | mariadb 07:23:43.06 INFO  ==> ** Starting MariaDB **
mariadb_1  | 2020-10-23  7:23:43 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.25-MariaDB) starting as process 1 ...
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Using Linux native AIO
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Uses event mutexes
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Number of pools: 1
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Waiting for purge to start
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: 10.3.25 started; log sequence number 1625506; transaction id 21
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_1  | 2020-10-23  7:23:43 0 [Note] InnoDB: Buffer pool(s) load completed at 201023  7:23:43
mariadb_1  | 2020-10-23  7:23:43 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2020-10-23  7:23:43 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1  | 2020-10-23  7:23:43 0 [Warning] 'proxies_priv' entry '@% root@bb30a08b87c2' ignored in --skip-name-resolve mode.
mariadb_1  | 2020-10-23  7:23:43 0 [Note] Reading of all Master_info entries succeeded
mariadb_1  | 2020-10-23  7:23:43 0 [Note] Added new Master_info '' to hash table
mariadb_1  | 2020-10-23  7:23:43 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.3.25-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
mariadb_1  | 2020-10-28  9:54:26 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (initiated by: unknown): Normal shutdown
mariadb_1  | 2020-10-28  9:54:26 0 [Note] Event Scheduler: Purging the queue. 0 events
mariadb_1  | 2020-10-28  9:54:26 0 [Note] InnoDB: FTS optimize thread exiting.
mariadb_1  | 2020-10-28  9:54:26 0 [Note] InnoDB: Starting shutdown...
mariadb_1  | 2020-10-28  9:54:26 0 [Note] InnoDB: Dumping buffer pool(s) to /bitnami/mariadb/data/ib_buffer_pool
mariadb_1  | 2020-10-28  9:54:26 0 [Note] InnoDB: Buffer pool(s) dump completed at 201028  9:54:26
mariadb_1  | 2020-10-28  9:54:27 0 [Note] InnoDB: Shutdown completed; log sequence number 1625515; transaction id 22
mariadb_1  | 2020-10-28  9:54:27 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mariadb_1  | 2020-10-28  9:54:27 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: Shutdown complete
mariadb_1  |
mariadb_1  | mariadb 09:54:44.89
mariadb_1  | mariadb 09:54:44.89 Welcome to the Bitnami mariadb container
mariadb_1  | mariadb 09:54:44.89 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | mariadb 09:54:44.89 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | mariadb 09:54:44.89
mariadb_1  | mariadb 09:54:44.89 INFO  ==> ** Starting MariaDB setup **
mariadb_1  | mariadb 09:54:44.91 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1  | mariadb 09:54:44.91 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | mariadb 09:54:44.91 INFO  ==> Initializing mariadb database
mariadb_1  | mariadb 09:54:44.92 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb_1  | mariadb 09:54:44.93 INFO  ==> Setting user option
mariadb_1  | mariadb 09:54:44.93 INFO  ==> Using persisted data
mariadb_1  | mariadb 09:54:44.95 INFO  ==> Running mysql_upgrade
mariadb_1  | mariadb 09:54:44.96 INFO  ==> Starting mariadb in background
mariadb_1  | mariadb 09:54:47.16 INFO  ==> Stopping mariadb
mariadb_1  |
mariadb_1  | mariadb 09:54:50.17 INFO  ==> ** MariaDB setup finished! **
mariadb_1  | mariadb 09:54:50.18 INFO  ==> ** Starting MariaDB **
mariadb_1  | 2020-10-28  9:54:50 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.25-MariaDB) starting as process 1 ...
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Using Linux native AIO
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Uses event mutexes
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Number of pools: 1
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Waiting for purge to start
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: 10.3.25 started; log sequence number 1625524; transaction id 21
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_1  | 2020-10-28  9:54:50 0 [Note] InnoDB: Buffer pool(s) load completed at 201028  9:54:50
mariadb_1  | 2020-10-28  9:54:50 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2020-10-28  9:54:50 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1  | 2020-10-28  9:54:50 0 [Warning] 'proxies_priv' entry '@% root@bb30a08b87c2' ignored in --skip-name-resolve mode.
mariadb_1  | 2020-10-28  9:54:50 0 [Note] Reading of all Master_info entries succeeded
mariadb_1  | 2020-10-28  9:54:50 0 [Note] Added new Master_info '' to hash table
mariadb_1  | 2020-10-28  9:54:50 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.3.25-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
matomo_1   |
matomo_1   | Welcome to the Bitnami matomo container
matomo_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
matomo_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues
matomo_1   |
matomo_1   | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
matomo_1   | nami    INFO  Initializing php
matomo_1   | nami    INFO  php successfully initialized
matomo_1   | nami    INFO  Initializing apache
matomo_1   | nami    INFO  apache successfully initialized
matomo_1   | nami    INFO  Initializing mysql-client
matomo_1   | nami    INFO  mysql-client successfully initialized
matomo_1   | nami    INFO  Initializing matomo
matomo_1   | Error executing 'postInstallation': "size" argument must not be negative
matomo_1   |
matomo_1   | Welcome to the Bitnami matomo container
matomo_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
matomo_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues
matomo_1   |
matomo_1   | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
matomo_1   | nami    INFO  Initializing matomo
matomo_1   | Error executing 'postInstallation': "size" argument must not be negative

**Describe the results you expected:**

the installation is to go through

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:41 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:11:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-118-generic
 Operating System: Ubuntu 16.04.7 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.64GiB
 Name: node-XXX-XXX-XXX-XXX
 ID: 7R5O:NMWO:CDQT:XNTU:P3Z7:UI2L:DWTM:F7FT:WHRA:ISBE:MOX3:ZFBV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VM - 16.04.1-Ubuntu

docker-compose content

version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=matomo
      - MARIADB_DATABASE=mxe_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - ./data/mariadb_data:/bitnami
  matomo:
    image: 'bitnami/matomo:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=matomo
      - MATOMO_DATABASE_NAME=mxe_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MATOMO_USERNAME=admin
      - MATOMO_PASSWORD=adminadmin
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - ./data/matomo_data:/bitnami
      - ./certs:/opt/bitnami/apache/conf/bitnami/certs
      - ./conf/bitnami.conf:/opt/bitnami/apache/conf/bitnami/bitnami.conf
      - ./conf/001-http-vhost.conf:/opt/bitnami/apache/conf/vhosts/001-http-vhost.conf:ro

$cat bitnami.conf
# Default Virtual Host configuration.

# Let apache know we're behind a SSL reverse proxy
SetEnvIf X-Forwarded-Proto https HTTPS=on

Include "/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf"

<VirtualHost _default_:80>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
#  RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
  RewriteRule ^/(.*) https://node-XXX-XXX-XXX-XX.domain.com/$1 [R,L]

  <Directory "/opt/bitnami/apache/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

  # Error Documents
  ErrorDocument 503 /503.html

</VirtualHost>

$cat 001-http-vhost.conf
AddType application/x-httpd-php .php

<VirtualHost  127.0.0.1:80  _default_:80 localhost:80>
  ServerAlias *
  DocumentRoot /opt/bitnami/matomo
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
  RewriteRule ^/(.*) https://node-XXX-XXX-XXX-XX.domain.com/$1 [R,L]

</VirtualHost>

**Comment by FraPazGal** [comment]
Hi @ematpad,

Thanks for using our container! I'm not sure about this line in `bitnami.conf`:

```
Include "/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf"
```

From the volumes you are mounting, I can't see the file `bitnami-ssl.conf`. Is it already present?

Also, could you please use the env `NAMI_DEBUG="log-level=trace"` and paste the given info?
