### ISSUE TITLE
File to delete: vendor/bin/lessc

### ISSUE THREAD

**Issue by dawidmalina** [bitnami/bitnami-docker-matomo#68]
**Description**

**Steps to reproduce the issue:**

1. Run latest 4.1.0 image
2. Login and check system check page
3. Check File integrity issue

**Describe the results you received:**

```
Files were found in your Matomo, but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: vendor/bin/lessc


To delete all these files at once, you can run this command:
rm "/opt/bitnami/matomo/vendor/bin/lessc"
```

**Describe the results you expected:**

No issues related to file integrity

**Comment by Findus23** [comment]
Hi,

https://github.com/matomo-org/matomo-package/pull/124 should fix this.

**Comment by FraPazGal** [comment]
Hello @dawidmalina,

As @Findus23 pointed (thanks for that!), this seems to be an issue from the source code. Once they implement the fix in the next release, we will re-compile our container and solve the issue in our catalog as well!

**Comment by juan131** [comment]
Latest version still contains the `less` binary.

**Comment by dawidmalina** [comment]
Upstream issue has been closed (fixed).
