### ISSUE TITLE
Can you provide "assume_protocol_secure" as environment variable?

### ISSUE THREAD

**Issue by MarcelMYSchmitt** [bitnami/bitnami-docker-matomo#71]
Hi, 

at first, thank you for "3.14.1-debian-10-r79", that's exactly what i needed! I had problems with root Matomo images in our Kubernetes Cluster, but with this version it's working now 🎉 

I've set up Matomo with an NGINX proxy because i had some problems with the Matomo Configration: https://matomo.org/faq/how-to-install/faq_98/

My Matomo is running (as described in the FAQ) behind a proxy and in sub-path ("/matomo"). When i try to only use the "MATOMO_ENABLE_PROXY_URI_HEADER" variable i still have the problem, that Matomo does not know, that it's already running under https. My current solution is to mount a "config.ini.php" and index.html file (in bitnami/matomo/* folders container) where assume_protocol_secure is set to 1 after i installed Matomo. It's okay, but not very nice because I'm working with if / else statements in my helm chart. 

Can you maybe add this to the environment variables? :)

Greetings
Marcel

**Comment by dhoppe** [comment]
@MarcelMYSchmitt Is this related to the System Check during the installation of Matomo?

```
Forced SSL Connection | We recommend using Matomo over secure SSL connections only. Please click here continue the installation process over SSL.
```

You just need to add ```X-Forwarded-Proto``` to you Nginx config.  
```
    location /matomo/ {
        proxy_pass http://matomo:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Uri /matomo;
    }
```

**Comment by jeffmacdonald** [comment]
Forgive me if I'm wrong for adding here, but I think I'm experiencing something very similar. I am standing up this docker container behind AWS ALB, and running the container in ECS. I'm pointing ECS at port 8443 and each time I try to login I get : "Error: Form security failed. Please reload the form and check that your cookies are enabled. If you use a proxy server, you must configure Matomo to accept the proxy header that forwards the Host header. Also, check that your Referrer header is sent correctly."

Does that seem related? Thanks.

**Comment by carrodher** [comment]
It may be related, yes, can you try the above-proposed workarounds? Due to the capacity of the team and the rest of the priorities that we have, the task is in our backlog, and, regrettably, at this moment I can't provide a specific ETA for this task.

**Comment by jeffmacdonald** [comment]
Just to come full circle. it wasn't related. I was running 2 instances and when I diff the config files, it looks like the salt is different between them. So I have to come up with a synchronization method.

**Comment by carrodher** [comment]
Thanks for letting us know!

**Comment by MarcelMYSchmitt** [comment]
Sorry for late reply. In my opinion it has nothing to do with the installation itself. 

Here is a code snippet from my nginx conf file.

``
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Proxy "";      
        proxy_set_header X-Forwarded-Uri /{{ .Values.nginx.matomoProxyPath }};
``

When i try to login without setting the assume protocol variable explicitly (only with my mounted nginx conf) I still get the warning, that the site is unsecure and if I Want to login into Matomo a message is shown on the login page. I do not have a screenshot but there is something like "contact your administrator" and "you can set following variable in your init.config.file". 

[General]
assume_secure_protocol = 1

So here is the code snippet from my matomo conf file.

``
     [General]
    proxy_uri_header = {{ .Values.matomo.env.matomoProxyUriHeader }} 
    assume_secure_protocol = {{ .Values.matomo.env.assumeSecureProtocol }} 
    enable_trusted_host_check = 0
``

And with this constelation it works without any problems.

**Comment by miguelaeh** [comment]
Hi @MarcelMYSchmitt ,
Thank you very much for sharing your work around, we will have it into account for the internal task
Regards

**Comment by JMLX42** [comment]
Here is a workaround using Ansible's `lineinfile`:

https://github.com/democratech/2022/issues/33#issuecomment-862305370

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-matomo#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
