### ISSUE TITLE
Modify Apache logs with Forwarded IP ( matomo under reverse proxy)

### ISSUE THREAD

**Issue by valentinab25** [bitnami/bitnami-docker-matomo#80]
Hello,

We are using matomo ( tested with bitnami/matomo:4.2.0 ) behind a reverse proxy. All the logs in matomo contain the local IP of the proxy.

Is it possible to add this code in the apache configuration, /opt/bitnami/apache/conf/httpd.conf, in the  module log_config_module : 

`
     LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
     `

And instead of "`    CustomLog "logs/access_log" common`"
```

     SetEnvIf X-Forwarded-For "^.*..*..*..*" forwarded
     CustomLog "logs/access_log" common env=!forwarded
     CustomLog "logs/access_log" proxy env=forwarded


```

This configuration allows you to view the client IP  in the Matomo Apache logs when you are  both using and not using a reverse proxy. I have tested the code in bitnami/matomo:4.2.0 and it works correctly ( forwarded IP from proxy and local ip if you connect directly). 

The other idea is to have an environment variable for apache under proxy that sets the correct log format on docker container start, if you don't want to use conditions.

Thank you

**Comment by carrodher** [comment]
Hi, currently the image already supports different methods to customize it, in order to add custom configuration files such as `httpd.conf`, can you take a look at the following sections in the README?

- https://github.com/bitnami/bitnami-docker-apache#customize-this-image
- https://github.com/bitnami/bitnami-docker-apache#full-configuration
- https://github.com/bitnami/bitnami-docker-apache#adding-custom-virtual-hosts

**Comment by valentinab25** [comment]
Hi Carlos,

Regarding the three methods:
-  The Virtual hosts method is for adding configuration, not modifying it.
-  Maintaining a separate matomo image does not justify the small
modification on apache logs
-  Regarding having httpd.conf on a volume - I noticed that this is not
easily maintainable. The configuration is not static for all upgrades ( for
example to migrate from 3 to 4 the old configuration was useless)

I thought to use
https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/post-init.sh
script to run the sed commands on the apache configuration, but it seems to
be broken. I'm not sure why you need both /docker-entrypoint-init.d/*.sh
and /post-init.d/*.sh locations, and even more,  the file
/bitnami/matomo/.user_scripts_initialized  is saved in a volume (
/bitnami), so the post-init scripts are not run on every container
re-create, only on first ever run.

The idea of fixing the apache logging configuration to work under proxy
makes sense because I am sure that most use matomo with a proxy ( mandatory
if you want clustering)

Thank you,
Valentina




<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by carrodher** [comment]
It is difficult for us to provide a generic image covering the different use cases our uses can have, that is the main reason why we try to add different customization options to the bitnami images.

Regarding this specific topic, I personally think the best option is to extend the image by adding the desired changes, but there is also possible to include those modifications in the configuration by default. The code is publicly available in this repository, for example, there are some modifications related to the apache configuration in [this file](https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libapache.sh), for example using the `replace_in_file` function you can modify the config file, see [this method](https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libapache.sh#L202). You can provide the required information in the PR with the changes and the team will be happy to review it and help you in the implementation, if finally, we consider the changes are in a good shape, they will be part of the image without any customization.
