### ISSUE TITLE
Facilitate the run of matomo/console from docker CMD 

### ISSUE THREAD

**Issue by valentinab25** [bitnami/bitnami-docker-matomo#81]
Hello,

We are using containers to periodically run matomo console commands ( like LDAP sync or data delete). Because running the console needs the matomo configuration to be already present in the matomo container, you first need to run the init scripts for it.
The problem is that the init scripts are only run if the script is [run.sh] (https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/matomo/entrypoint.sh#L20)

Is it possible to add the same scripts for the command: `php /opt/bitnami/matomo/console` ? Like this:

`if [[ "$1" = "/opt/bitnami/scripts/$(web_server_type)/run.sh" || "$1" = "/opt/bitnami/scripts/nginx-php-fpm/run.sh" || "$1" = "/opt/bitnami/scripts/matomo/run.sh" ]] || "$1 $2" = "php /opt/bitnami/matomo/console" ]] ; then`

Thank you

**Comment by rafariossaa** [comment]
Hi,
 I am not very sure or your use case, you can start a matomo deployment with `docker-compose up` and latter issue commands to that deployment with `docker exec`. Would that work for you ?

**Comment by valentinab25** [comment]
Hi Rafael,

We are using rancher for our stacks and rancher-crontab to periodically
start containers, so running docker exec is not an option.
I usually set the entrypoint to run/include the scripts from the
docker-entrypoint.sh , adding the console command, but I thought it would
be simpler if console commands were supported by default, especially
because the scripts tend to change on upgrades.


Thank you
Valentina


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rafariossaa** [comment]
Would it work for you if you mount the volume from the running matomo instance ?
