### ISSUE TITLE
Could not connect to the database server

### ISSUE THREAD

**Issue by monodop** [bitnami/bitnami-docker-matomo#85]
**Description**

Trying to connect to the database with the MYSQL_CLIENT_ env vars

It works when I try connecting from the command line inside the image using the mysql command

It would be really nice if the error message told me what the error was from the mysql command. Did it timeout? Was there a firewall issue? Was the password incorrect? Was my hostname blocked from remote access? Etc

It seems like the docker image swallows the error in `libmysqlclient.sh`

Is there a way to get this information from the scripts? Like a verbose env var?

**Describe the results you received:**

Could not connect to the database server

**Describe the results you expected:**

Connects to the database server

**Version**

Rancher: v2.5.3
Helm: v2.16.8-rancher1
Machine: v0.15.0-rancher46
bitnami-docker-matomo: 4.2.1

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running in rancher kubernetes stack with a mysql server on a dedicated VM

**Comment by monodop** [comment]
Ok, I found out about `BITNAMI_DEBUG=true` after searching around a bit more in the issues. Can this be documented in the main documentation somewhere? I spent forever trying to figure this out, not realizing that was a thing. I had assumed it didn't exist because it wasn't in the docs.

**Comment by migruiz4** [comment]
Hi @monodop,

I'm sorry for the inconvenience, I will add `BITNAMI_DEBUG` to the README to prevent other users from running into the same issue.

Where you able to solve your connectivity issue after increasing the logs verbosity?

**Comment by monodop** [comment]
Yup! It ended up being a mix of some database permission issues.

**Comment by migruiz4** [comment]
Great! I'm glad you were able to find and resolve the issue.
