### ISSUE TITLE
Links to Docker Hub broken (404)

### ISSUE THREAD

**Issue by itssimon** [bitnami/bitnami-docker-matomo#86]
https://hub.docker.com/r/bitnami/matomo

Shows "Page Not Found".

**Comment by Findus23** [comment]
Hi,

See https://github.com/bitnami/bitnami-docker-matomo/issues/74 for more information.

The page is working fine, but your adblocker is blocking the request with the Information about the docker image (as it contains Matomo) and therefore the docker website decides to show "Page Not Found"

**Comment by Findus23** [comment]
This pull request to the Easylist blocking list will fix the adblocker, but it hasn't been merged yet: https://github.com/easylist/easylist/pull/6797

**Comment by itssimon** [comment]
Interesting, thanks for clarifying!

**Comment by Findus23** [comment]
Just FYI: The issue should now be fixed with https://github.com/easylist/easylist/commit/3293ab6042b5d1927a67afdd838b5ff38e478061

**Comment by miguelaeh** [comment]
Thank you @Findus23 for replying!
