### ISSUE TITLE
Connect to existing RDS database

### ISSUE THREAD

**Issue by gladsonvm** [bitnami/bitnami-docker-matomo#88]
Thanks for the wonderful matomo docker deployment solution! Is it possible to connect to an existing RDS database by specifying database params as environment variables? I went through the code and cannot find where it is asking for database password in the case of RDS. If this feature is there a remote DB can be used instead of local database setup.

**Comment by Mauraza** [comment]
Hi @gladsonvm,

Could you try to use these variables https://github.com/bitnami/bitnami-docker-matomo#use-an-existing-database to configure an RDS database?

**Comment by gladsonvm** [comment]
Thanks for the info. I am able to connect to rds now :)

**Comment by Mauraza** [comment]
Hi @gladsonvm,

In addition to these variables, you must add these:
#### Connection credentials for mysql-client
-  MYSQL_CLIENT_DATABASE_HOST
- MYSQL_CLIENT_DATABASE_PORT_NUMBER
- MYSQL_CLIENT_DATABASE_ROOT_USER
- MYSQL_CLIENT_DATABASE_ROOT_PASSWORD
####  Create database and a user to connect to it
- MYSQL_CLIENT_CREATE_DATABASE_NAME
- MYSQL_CLIENT_CREATE_DATABASE_USER
- MYSQL_CLIENT_CREATE_DATABASE_PASSWORD

**Comment by gladsonvm** [comment]
Still not able to connect to rds :(. I updated with all env varibales.  Logs below

> docker-compose up
Creating network "home_default" with the default driver
Creating volume "home_mariadb_data" with local driver
Creating volume "home_matomo_data" with local driver
Creating home_mariadb_1 ...
Creating home_mariadb_1 ... done
Creating home_matomo_1  ...
Creating home_matomo_1  ... done
Docker Compose is now in the Docker CLI, try `docker compose up`

Attaching to home_mariadb_1, home_matomo_1
mariadb_1  | mariadb 09:00:03.69
mariadb_1  | mariadb 09:00:03.69 Welcome to the Bitnami mariadb container
mariadb_1  | mariadb 09:00:03.69 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | mariadb 09:00:03.69 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | mariadb 09:00:03.69
matomo_1   | matomo 09:00:04.11
mariadb_1  | mariadb 09:00:03.69 INFO  ==> ** Starting MariaDB setup **
mariadb_1  | mariadb 09:00:03.71 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1  | mariadb 09:00:03.71 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | mariadb 09:00:03.71 INFO  ==> Initializing mariadb database
mariadb_1  | mariadb 09:00:03.72 INFO  ==> Updating 'my.cnf' with custom configuration
matomo_1   | matomo 09:00:04.11 Welcome to the Bitnami matomo container
mariadb_1  | mariadb 09:00:03.72 INFO  ==> Setting user option
mariadb_1  | mariadb 09:00:03.74 INFO  ==> Installing database
matomo_1   | matomo 09:00:04.11 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
matomo_1   | matomo 09:00:04.12 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues
matomo_1   | matomo 09:00:04.12
matomo_1   | matomo 09:00:04.12 INFO  ==> ** Starting Matomo setup **
matomo_1   | matomo 09:00:04.14 INFO  ==> Configuring PHP options
matomo_1   | matomo 09:00:04.15 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
matomo_1   | matomo 09:00:04.17 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
matomo_1   | matomo 09:00:04.19 INFO  ==> Ensuring Matomo directories exist
matomo_1   | matomo 09:00:04.20 INFO  ==> Trying to connect to the database server
mariadb_1  | mariadb 09:00:06.82 INFO  ==> Starting mariadb in background
mariadb_1  | mariadb 09:00:08.85 INFO  ==> Configuring authentication
mariadb_1  | mariadb 09:00:08.92 INFO  ==> Running mysql_upgrade
mariadb_1  | mariadb 09:00:09.28 INFO  ==> Stopping mariadb
mariadb_1  |
mariadb_1  | mariadb 09:00:12.88 INFO  ==> ** MariaDB setup finished! **
mariadb_1  | mariadb 09:00:12.90 INFO  ==> ** Starting MariaDB **
mariadb_1  | 2021-06-22  9:00:12 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.29-MariaDB) starting as process 1 ...
mariadb_1  | 2021-06-22  9:00:12 0 [Note] InnoDB: Using Linux native AIO
mariadb_1  | 2021-06-22  9:00:12 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1  | 2021-06-22  9:00:12 0 [Note] InnoDB: Uses event mutexes
mariadb_1  | 2021-06-22  9:00:12 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1  | 2021-06-22  9:00:12 0 [Note] InnoDB: Number of pools: 1
mariadb_1  | 2021-06-22  9:00:12 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: Waiting for purge to start
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: 10.3.29 started; log sequence number 1625452; transaction id 20
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_1  | 2021-06-22  9:00:13 0 [Note] InnoDB: Buffer pool(s) load completed at 210622  9:00:13
mariadb_1  | 2021-06-22  9:00:13 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2021-06-22  9:00:13 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1  | 2021-06-22  9:00:13 0 [Warning] 'proxies_priv' entry '@% root@93d40b4c189d' ignored in --skip-name-resolve mode.
mariadb_1  | 2021-06-22  9:00:13 0 [Note] Reading of all Master_info entries succeeded
mariadb_1  | 2021-06-22  9:00:13 0 [Note] Added new Master_info '' to hash table
mariadb_1  | 2021-06-22  9:00:13 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.3.29-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
matomo_1   | matomo 09:01:04.39 ERROR ==> Could not connect to the database
home_matomo_1 exited with code 1

I am using ssh tunnel to connect to rds. Connection is healthy and I can telnet to the port (3306-->3306) without any issues
ENV VARS as below

      - MATOMO_DATABASE_HOST=localhost
      - MATOMO_DATABASE_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=<dbuser>
      - MATOMO_DATABASE_NAME=<dbname>
      - MATOMO_DATABASE_PASSWORD=<dbpassword>
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_CLIENT_DATABASE_HOST=localhost
      - MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306
      - MYSQL_CLIENT_DATABASE_ROOT_USER=<dbrootuser>
      - MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=<dbrootpass>
      - MYSQL_CLIENT_FLAVOR=mysql

**Comment by Mauraza** [comment]
Hi @gladsonvm,

Could you add the `BITNAMI_DEBUG=true` environment variable and try again to get more information in the logs?

**Comment by aayush27894** [comment]
Please check out the following link: https://github.com/bitnami/bitnami-docker-matomo/issues/83
