### ISSUE TITLE
Use proxy for outbound requests

### ISSUE THREAD

**Issue by adberger** [bitnami/bitnami-docker-matomo#90]
**Description**

Is it possible to add proxy to container for outbound requests as described here: https://matomo.org/faq/troubleshooting/faq_121/
Or do I have to write a post-init script?

**Comment by juan131** [comment]
Hi @adberger 

The Matomo container uses Apache to serve Matomo. That said, you can use a second container to a act as proxy such as [NGINX Proxy](https://github.com/nginx-proxy/nginx-proxy).

It's quite a common solution used on containers.

**Comment by adberger** [comment]
> Hi @adberger
> 
> The Matomo container uses Apache to serve Matomo. That said, you can use a second container to act as proxy such as [NGINX Proxy](https://github.com/nginx-proxy/nginx-proxy).
> 
> It's quite a common solution used on containers.

But it's for outgoing traffic (matomo -> internet).
How to tell matomo to use the proxy then?

**Comment by juan131** [comment]
Hi @adberger 

In a similar way you can configure a NGINX container to act as a "Forward Proxy". Find more information in guide like the one below:

- https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/

For instance, if you use the [Bitnami NGINX container](https://github.com/bitnami/bitnami-docker-nginx), you can use the steps below to deploy it using your custom configuration file so you can customize it to act as a forward proxy.

- https://github.com/bitnami/bitnami-docker-nginx#full-configuration

Then, you need to configure Matomo, as described in the guide you shared, to use this NGINX container as rpxoy.

**Comment by adberger** [comment]
> Hi @adberger
> 
> In a similar way you can configure a NGINX container to act as a "Forward Proxy". Find more information in guides like the one below:
> 
> * https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/
> 
> For instance, if you use the [Bitnami NGINX container](https://github.com/bitnami/bitnami-docker-nginx), you can use the steps below to deploy it using your custom configuration file so you can customize it to act as a forward proxy.
> 
> * https://github.com/bitnami/bitnami-docker-nginx#full-configuration
> 
> Then, you need to configure Matomo, as described in the guide you shared, to use this NGINX container as proxy.

Hi @juan131 

I think you misunderstood my initial question :)
We already have a Forward Proxy.

My question is how to configure the proxy in this bitnami-docker-matomo image without writing our own Dockerfile.

I tried to mount an additional file called `config.ini.php` in the directory `/opt/bitnami/php/conf` with the following configuration, which didn't work:
```
[proxy]
host = proxy.example.com
port = 8080
```

**Comment by juan131** [comment]
Oh sorry.. You're simply interested on how to extend the Matomo configuration with your custom block, right?

**Comment by adberger** [comment]
> Oh sorry.. You're simply interested on how to extend the Matomo configuration with your custom block, right?

Yes :)

**Comment by juan131** [comment]
We don't have a way to extend the configuration file that's based on env. variables. However, you can use a custom post-init script to do any custom action.

As you can see in the **entrypoint**.sh, the [post-init.sh](https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/post-init.sh) script is executed right after setting up Matomo:

- https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/matomo/entrypoint.sh#L26

This `post-init.sh` script looks for custom scripts mounted in the `/docker-entrypoint-init.d` path of the container and execute them the 1st time the container is launched.

Therefore, you can mount a custom script (e.g. `configure-proxy.sh`) with the content below:

```bash
#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

# Load Matomo environment
. /opt/bitnami/scripts/matomo-env.sh

# Load libraries
. /opt/bitnami/scripts/libmatomo.sh

ini-file set -s "proxy" -k "host" -v "proxy.example.com" "$MATOMO_CONF_FILE"
ini-file set -s "proxy" -k "port" -v "8080" "$MATOMO_CONF_FILE"
```

**Comment by adberger** [comment]
Thank you very much!
We implemented as you suggested, closed.
