### ISSUE TITLE
How the modify the root url of matomo

### ISSUE THREAD

**Issue by beichen-xing** [bitnami/bitnami-docker-matomo#92]
Hello, I can successfully run the `docker.io/bitnami/matomo:4 `at http://localhost/index.php 
However, I try to edit the root url of the application to be like http://localhost/matomo/index.php, to let the application runs in a subfolder. Are there any ways I can do it?

Many thanks in advance

**Comment by Mauraza** [comment]
Hi @beichen-xing,

Did you try to use `MATOMO_WEBSITE_HOST` to configure the host? You can find some environment variables in https://github.com/bitnami/bitnami-docker-matomo#user-and-site-configuration

**Comment by beichen-xing** [comment]
> Hi @beichen-xing,
> 
> Did you try to use `MATOMO_WEBSITE_HOST` to configure the host? You can find some environment variables in https://github.com/bitnami/bitnami-docker-matomo#user-and-site-configuration

Thanks for your reply. However, I got "URL not found error" after I set the MATOMO_WEBSITE_HOST as http://localhost/matomo/, which indicates the root URL is still not changed. Because the docker will go to localhost firstly, then try finding /matomo.

**Comment by Mauraza** [comment]
Hi @beichen-xing,

Could you try with a `domain`?

**Comment by beichen-xing** [comment]
Thanks! Got the same error with `domain`. Maybe there is something that needs to be done in the apache server inside the docker I guess.
