### ISSUE TITLE
4.4.0 Matomo Docker images

### ISSUE THREAD

**Issue by kevin-shelaga** [bitnami/bitnami-docker-matomo#93]
**Description**
Add 4.4.0 Matomo Docker images

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by pablogalegoc** [comment]
Hi @kevin-shelaga,

We appreciate your interest! What I can tell you is that our pipeline has already detected this new minor version and given that it is just a maintenance release it should be a matter of time that it will get released, but I cannot provide a specific ETA.

**Comment by kevin-shelaga** [comment]
@pablogalegoc Thank you, there are some breaking changes and an added feature that is important to us.

**Comment by pablogalegoc** [comment]
Oh, I see, I read just the release announcement. In that case it might get delayed a bit if it gets stuck on some tests but the team will handle it. I’ll leave this issue open in case I got news.

**Comment by kevin-shelaga** [comment]
Looks like a new 4.4.0 build was pushed, thank you
