### ISSUE TITLE
time zone

### ISSUE THREAD

**Issue by zlchanger** [bitnami/bitnami-docker-matomo#96]
Hi, how do I set the time zone of the matomo web page?
Is there an environment variable that provides time zone settings? 
I have changed Debian's time zone and there is no problem viewing it through the 'date' command
Thank you!

**Comment by juan131** [comment]
Hi @zlchanger 

Please check the issue below (from Dokuwiki container) where we discussed a similar topic and let us know if that helps:

- https://github.com/bitnami/bitnami-docker-dokuwiki/issues/43

**Comment by zlchanger** [comment]
OK,thank you!
