### ISSUE TITLE
force_ssl configuration in config/config.ini.php

### ISSUE THREAD

**Issue by zlchanger** [bitnami/bitnami-docker-matomo#97]
Thank you for checking my questions！

How do I configure "assume_secure_protocol" and "force_ssl" in file (config/config.ini.php), whether such environment variables (similar to database configuration) are provided. PS when using the docker command.

**Comment by pablogalegoc** [comment]
Hi @zlchanger!

Currently you'll have to extend the image to support this. Should be a matter of adding new conditions like this:
https://github.com/bitnami/bitnami-docker-matomo/blob/4dd87972c7b2d60276f9245d38f137b85db9263d/4/debian-10/rootfs/opt/bitnami/scripts/libmatomo.sh#L170-L175

**Comment by zlchanger** [comment]
OK, thank you. It's completely feasible
